name = "Time-2012-EST-hourly-periodBeginning-noDST-noLeapDayAdjustment-total"
type = "time"
id = "time-2012-est-hourly-periodbeginning-nodst-noleapdayadjustment-total__fb22095d-4749-42cd-a37e-76020706f3b3"
module = "dsgrid.dimension.standard"
class = "Time"
description = "Time dimension, 2012 hourly EST, period-beginning, no DST, no Leap Day Adjustment, total value"
model_hash = "8ee83c159e2190adc29e2dbf5374f810a7104047b70a0935d649db43b73eccb5"
time_type = "datetime"
measurement_type = "total"
str_format = "%Y-%m-%d %H:%M:%S"
frequency = "P0DT1H0M0.000000S"
leap_day_adjustment = "none"
time_interval_type = "period_beginning"
timezone = "EasternStandard"
[[ranges]]
start = "2012-01-01 00:00:00"
end = "2012-12-31 23:00:00"

