version = "1.0.0"
description = "US Census Regions"
dimension_id = "us_census_regions__b3125c78-0173-4dfa-808e-57accbb2d18b"
[[registration_history]]
version = "1.0.0"
submitter = "dthom"
date = "2021-09-14T07:51:56.192334"
log_message = "Initial registration"

