mapping_type = "one_to_one"
archetype = "one_to_one_map_fraction_sum_from_id_eq1"
description = "ResStock CONUS 2022 counties to project counties"
id = "conus_2022-resstock_us_county_fip__us_counties_2020_l48__ba39ade4-e833-428a-8650-4f7a9cba6edb"
file = "county_to_county.csv"
file_hash = "860cf52971a8000da6a0f0ee7e7e6ed1c6e77602bd77c4f4311be35e98140637"

[from_dimension]
type = "geography"
dimension_id = "conus_2022-resstock_us_county_fip__46811eca-4652-4670-8144-30c0f3a6a6da"
version = "1.0.0"

[to_dimension]
type = "geography"
dimension_id = "us_counties_2020_l48__cc913019-cfc3-496c-acec-fe9d3457e44d"
version = "1.0.0"
