version = "1.0.0"
description = "Data source: ComStock"
dimension_id = "comstock-data-source__e44a2040-5965-45a2-935b-06f3eb3c7cf9"
[[registration_history]]
version = "1.0.0"
submitter = "lliu2"
date = "2022-08-01T17:19:32.770059"
log_message = "Initial registration"

