mapping_type = "one_to_one"
archetype = "one_to_one_map_fraction_sum_eq1"
description = "TEMPO CONUS 2022 End Uses to dsgrid CONUS 2022 End Uses w/ all units in kWh"
id = "tempo_ldv_pev_usage__conus-2022-detailed-end-uses-kwh__aa425565-c44b-4ae3-8512-778567314217"
file = "metric_to_metric.csv"
file_hash = "bc4c17a46da03818bdea747a3eec1f88978f27930eb03c8f69a02703823790fe"

[from_dimension]
type = "metric"
dimension_id = "tempo_ldv_pev_usage__ef95e63e-2947-46a4-b882-00c3569f48e5"
version = "1.0.0"

[to_dimension]
type = "metric"
dimension_id = "conus-2022-detailed-end-uses-kwh__ea5aa752-36b2-4a4c-929f-3dac5f397a94"
version = "1.0.0"
