data_source = "comstock"
dataset_id = "test_efs_comstock"
data_schema_type = "standard"
dataset_type = "sector_model"
trivial_dimensions = ["weather_year", "model_year", "scenario", "data_source"]
description = "EFS ComStock data translated into the new dsgrid data format"
origin_creator = "Henry Horsey"
origin_organization = "NREL"
origin_contributors = [ "Henry Horsey", "Amanda Farthing", "Andrew Parker",]
origin_project = "Electrification Futures Study (EFS)"
origin_date = "2018-06-18"
origin_version = "0.2.0"
source = "https://nrel.sharepoint.com/:u:/r/sites/dsgrid-load/Shared%20Documents/File%20Archive/fy17%20-%20OSP%20-%20Electrification%20Load%20Modeling/data/dsgrid_v0.2.0/data/commercial.dsg?csf=1&web=1&e=dU8Ogx"
data_classification = "low"
tags = [ "commercial", "efs", "2012", "dsgrid_v0.2.0",]

[data_schema]
load_data_column_dimension = "metric"

[[dimensions]]
class = "Subsector"
description = """EFS formated ComStock subsectors. Based on building types subsectors for ComStock, 14 DOE prototypes"""
file = "dimensions/comstock_subsectors.csv"
module = "dsgrid.dimension.standard"
name = "ComStock Subsectors EFS with formatted prefix"
display_name = "ComStock Building Type"
type = "subsector"

[[dimensions]]
class = "ModelYear"
description = """
Model year, 2012 only
"""
file = "dimensions/model_years.csv"
module = "dsgrid.dimension.standard"
name = "Model Year 2012"
display_name = "2012"
type = "model_year"

[[dimensions]]
class = "Time"
name = "Time-2012-EST-hourly-periodEnding-noDST-noLeapDayAdjustment-total-UTChour1start"
display_name = "2012 Hourly EST"
description = """
Time dimension, 2012 hourly EST, period-ending, no DST, no Leap Day Adjustment, total value
"""
ranges = [{start = "2012-01-01 01:00:00", end = "2012-01-08 00:00:00"}]
frequency = "01:00:00"
type = "time"
time_interval_type = "period_ending"
str_format = "%Y-%m-%d %H:%M:%S"
timezone = "EasternStandard"
measurement_type = "total"
time_type = "datetime"

[[dimension_references]]
dimension_id = "us_counties_2010_-_comstock_only__b913be60-d3da-407b-935b-6a1b8ee7d92c"
type = "geography"
version = "1.0.0"

[[dimension_references]]
dimension_id = "efs_sectors_-_comstock_only__0f03e3c1-f18b-4ec8-830d-6d93e5e007e3"
type = "sector"
version = "1.0.0"

[[dimension_references]]
dimension_id = "efs_detailed_end_uses_-_comstock_only__301852a1-7f7a-4479-9b76-c7cdc686f81b"
type = "metric"
version = "1.0.0"

[[dimension_references]]
dimension_id = "2012_weather_year__0019ebb9-507b-41c9-b5a4-383b97304a69"
type = "weather_year"
version = "1.0.0"

[[dimension_references]]
dimension_id = "reference_scenario__4b6defca-9212-4388-bc39-9cf4462b4527"
type = "scenario"
version = "1.0.0"

[[dimension_references]]
dimension_id = "comstock_data_source__d2f50c33-8b51-4b4d-a679-46114eb5244c"
type = "data_source"
version = "1.0.0"
