[[mappings]]
mapping_type = "one_to_one_explicit_multipliers"
description = "Maps EFS ComStock prefix-formatted subsectors to the EFS project subsectors"
file = "dimension_mappings/lookup_comstock_subsectors_to_project_subsectors.csv"
dimension_type = "subsector"

[[mappings]]
mapping_type = "duplication"
description = "Maps EFS ComStock model year EFS project model years"
file = "dimension_mappings/model_year_to_model_year.csv"
dimension_type = "model_year"

# TODO: do we need a dataset-to-project time to time dimension mapping?
