mapping_type = "many_to_one_aggregation"
archetype = "many_to_one_map_fraction_sum_eq1"
description = "Aggregation map for all data_sources"
id = "data-sources_-_comstock-resstock-tempo-only__all-data_sources__7b8157c8-c314-4dca-9529-82ddd7a45552"
file = "lookup_data_source_to_all_data_sources.csv"
file_hash = "8b1487cae6c577736e9f5d2cc719590f55887fb463429f1168919f9cb6670d04"

[from_dimension]
type = "data_source"
dimension_id = "data-sources_-_comstock-resstock-tempo-only__2019869a-27a7-4f0a-af46-bac90f584c4d"
version = "1.0.0"

[to_dimension]
type = "data_source"
dimension_id = "all-data_sources__f926014b-8cac-4519-b1c3-d5d1442402b1"
version = "1.0.0"
