name = "conus_2022-comstock_US_county_FIP"
display_name = "County"
dimension_query_name = "county"
type = "geography"
id = "conus_2022-comstock_us_county_fip__e26591ba-2aac-4059-8e45-a79915d6783e"
module = "dsgrid.dimension.standard"
class = "County"
description = "CONUS 2022 - ComStock US county in (older version) original FIP code (N=3,133),\nincludes 23 AK counties, 1 county renamed in 2015 (SD, Shannon County -> SD, Oglala Lakota County),\n1 city (VA, Bedford City) that is now part of a county (VA Bedford County)."
file = "conus_2022-comstock_geography_county_fips.csv"
file_hash = "77bce790e0886cbb94f6a1606398aee0be62b9df8091499cfbd6b58cbc042ebf"
