name = "CONUS-2022-Detailed-End-Uses-kWh"
display_name = "End Use"
dimension_query_name = "end_use"
type = "metric"
id = "conus-2022-detailed-end-uses-kwh__ea5aa752-36b2-4a4c-929f-3dac5f397a94"
module = "dsgrid.dimension.standard"
class = "EnergyEndUse"
description = "dsgrid CONUS 2022 End Uses (all fuel types) w/ all units in kWh"
file = "enduses_kwh.csv"
file_hash = "bccbb338271ee66fcece15a2a02ba9b76ea07b29bc004fa33b7c01b914c00c35"
