name = "all-data_sources"
display_name = "All Data_Sources"
dimension_query_name = "all_data_sources"
type = "data_source"
id = "all-data_sources__f926014b-8cac-4519-b1c3-d5d1442402b1"
module = "dsgrid.dimension.standard"
class = "DataSource"
description = "All Data_Sources"
file = "all_data_sources.csv"
file_hash = "649e840713c6bdde26ff853edcd35aaa63087730b2adfec141c4c8f3780a4877"
