name = "conus_2022-resstock_energy_enduses_kwh"
display_name = "ResStock End Use"
dimension_query_name = "resstock_end_use"
type = "metric"
id = "conus_2022-resstock_energy_enduses_kwh__1b980827-4dee-4025-adbc-8488f3377477"
module = "dsgrid.dimension.standard"
class = "EnergyEndUse"
description = "CONUS 2022 - ResStock end uses (N=48, 5 fuel types)"
file = "conus_2022-resstock_end_uses.csv"
file_hash = "b57107c85b8836eaed4d4fa1f45489a7479bd27b26a383e71c9662875ca97b9b"
