version = "1.1.0"
description = "dsgrid project for the 2018 Electrification Futures Study (EFS)"
project_id = "efs_2018"

[[registration_history]]
version = "1.1.0"
submitter = "dthom"
date = "2021-09-14T07:55:06.419035"
log_message = "Submitted ComStock data"

[[registration_history]]
version = "1.0.0"
submitter = "dthom"
date = "2021-09-14T07:51:56.332327"
log_message = "Initial registration"

