version = "1.0.0"
description = "US counties for L48, Census 2020 vintage, no territories"
dimension_id = "us_counties_2020_l48__cc913019-cfc3-496c-acec-fe9d3457e44d"
[[registration_history]]
version = "1.0.0"
submitter = "lliu2"
date = "2022-08-01T17:19:23.571898"
log_message = "Initial registration"

