name = "all-electric-end-uses"
display_name = "Electricity"
dimension_query_name = "electricity"
type = "metric"
id = "all-electric-end-uses__ba3f8784-76d8-419d-99a6-56e878b4dee7"
module = "dsgrid.dimension.standard"
class = "EnergyEndUse"
description = "All Electric End Uses"
file = "all_electric_enduses.csv"
file_hash = "78d862737dac5a6871eaf38439ac2934ebacb880726faa11dafa63635ef4a43b"
