version = "1.0.0"
description = "CONUS 2022 - ComStock building types (N=14)"
dimension_id = "conus_2022-comstock_building_types__97afade1-e38c-444d-ab5b-0078afe510fa"
[[registration_history]]
version = "1.0.0"
submitter = "lliu2"
date = "2022-08-01T17:19:32.770059"
log_message = "Initial registration"

