name = "TEMPO Model"
display_name = "TEMPO"
dimension_query_name = "tempo"
type = "data_source"
id = "tempo_model__44982884-32a1-45ba-8f89-4bdcd3af7eff"
module = "dsgrid.dimension.standard"
class = "DataSource"
description = "TEMPO model"
file = "data_source.csv"
file_hash = "b9e6b4a6a1246ac1d31ec1e661872c1ab3213573fc55348c6e615721c48b3d13"
