version = "1.0.0"
description = "Scenarios for the dsgrid CONUS 2022 project, which include a Reference scenario\nand two light-duty vehicle electrification scenarios"
dimension_id = "conus-2022-scenarios__20236bfb-ad56-48ef-9c61-2534bfc28e26"
[[registration_history]]
version = "1.0.0"
submitter = "lliu2"
date = "2022-08-01T17:19:23.571898"
log_message = "Initial registration"

