name = "TEMPO Model Year"
display_name = "TEMPO Model Years"
dimension_query_name = "tempo_model_years"
type = "model_year"
id = "tempo_model_year__294ca699-5fbf-48f8-824b-b788b279bb45"
module = "dsgrid.dimension.standard"
class = "ModelYear"
description = "TEMPO modeling years for CONUS 2022 project, 2018-2050"
file = "year.csv"
file_hash = "2d1b448af7bb91aa7bd282028fb612d86690c2c8ec9e4f7b0d0ad657977b2ce4"
