version = "1.0.0"
description = "Time dimension, 2012 hourly EST, hour-beginning, no Leap Day Adjustment, total value"
dimension_id = "time-2012-est-hourly-periodbeginning-noleapdayadjustment-total__17ed26c3-f9e4-4562-a221-07a9f8cb9999"
[[registration_history]]
version = "1.0.0"
submitter = "lliu2"
date = "2022-08-01T17:19:23.571898"
log_message = "Initial registration"

