version = "1.0.0"
description = "Aggregation map for all subsectors"
dimension_mapping_id = "conus-2022-detailed-subsectors__all-subsectors__0524e69f-0f83-4c7b-95dc-e252d3285d59"
[[registration_history]]
version = "1.0.0"
submitter = "lliu2"
date = "2022-08-01T17:19:30.073792"
log_message = "Initial registration"

