name = "US Counties 2010 - ComStock Only"
type = "geography"
id = "us_counties_2010_-_comstock_only__8164af10-b114-4c2f-888a-0d7810d46df9"
module = "dsgrid.dimension.standard"
class = "County"
description = "US counties 2010, no territories, AK, HI, and some other counties, only for ComStock"
model_hash = "1f4b276c6584e7b9d845f1435df180027b685e42f0a2077a10b3870962b7b586"
file = "comstock_counties.csv"
file_hash = "7ebb7434080bd1c9d20d56845512ef6fdcd76da7c7ced2c80b0b94c25a379c4a"
