name = "TEMPO Bin"
display_name = "Household and Vehicle Type"
dimension_query_name = "household_and_vehicle_type"
type = "subsector"
id = "tempo_bin__e4400ab0-2170-40d6-893e-5a1a6abb20b4"
module = "dsgrid.dimension.standard"
class = "Subsector"
description = "TEMPO demographic/geographic/vehicle bins.\n\nThis is a cross-join of the following supplemental dimensions:\n* Composition (Single Driver, Some Drivers Smaller, Some Drivers Larger)\n* Income (Low Income, Middle Income, High Income)\n* Urbanity (Rural, Small Town, Suburban, Second City, Urban)\n* Vehicle Size Class (Compact, Midsize, SUV, Pickup)\n* Tech (PHEV25/PHEV50/BEV100/BEV300)"
file = "bin.csv"
file_hash = "3bf6edb674891d7fbf7ce8ddd87030acf9791e4cb73f30273c21b2a0cbc9df37"
