version = "1.0.0"
description = "Model year, 2010-2050, every other year"
dimension_id = "model_years_2010_to_2050_with_2_year_intervals__7413fb04-6c15-496f-bd83-d835e26dd81b"
[[registration_history]]
version = "1.0.0"
submitter = "mmooney"
date = "2021-09-29T09:19:41.570631"
log_message = "Initial Registration"

