version = "1.0.0"
description = "US States"
dimension_id = "us_states__382f9209-f0ef-4ec1-80a5-59452847ec6c"
[[registration_history]]
version = "1.0.0"
submitter = "dthom"
date = "2021-09-14T07:51:56.192334"
log_message = "Initial registration"

