name = "Standard Scenarios 2021 Sectors - Com-Res-Tra-Only"
type = "sector"
id = "standard_scenarios_2021_sectors_-_com-res-tra-only__533c76e9-ee74-48d3-bb6d-5c2774a1d1ec"
module = "dsgrid.dimension.standard"
class = "Sector"
description = "dsgrid Standard Scenarios 2021 Sectors; Commercial, Residential, Transportation  Only"
model_hash = "abef176a5613700be0c3d6541a7c2cec47e36aefbd234b66a627ad2a78f22852"
file = "sectors.csv"
file_hash = "bad197c1d1fe1849ada6cc131c4050cba75801c619cb32a3e3a6d6d00e002adf"
