dataset_type = "benchmark"
data_source = "NEMS Commercial Module"
dataset_id = "aeo2021_ref_com_energy_end_uses"
data_schema_type = "one_table"
description = "AEO 2021 Reference Case Commercial Energy End Uses Projection: 2013-2050"
origin_creator = "Kevin Jarzomski"
origin_organization = "EIA"
origin_contributors = [ "Lixi Liu", "Meghan Mooney", "Elaine Hale",]
origin_project = "EIA AEO 2021"
origin_date = "2021-10-05"
origin_version = "0.1.0"
source = "Data extracted from AEO 2021 detailed commercial sector files sent from EIA"
data_classification = "low"
tags = [ "commercial", "benchmark", "projection", "aeo2021", "dsgrid_v0.2.0",]
trivial_dimensions = [ "sector", "scenario", "data_source", "weather_year", "model_year"]

[data_schema]
load_data_column_dimension = "metric"

[[dimensions]] # already exists
type = "geography"
name = "US_Census_Divisions"
display_name = "Census Division"
file = "dimensions/us_census_divisions.csv"
module = "dsgrid.dimension.standard"
class = "CensusDivision"
description = """
US Census Divisions (N=9)
"""

[[dimensions]] # already exists
type = "sector"
name = "commercial-sector"
display_name = "Commercial"
file = "dimensions/sector_commercial.csv"
module = "dsgrid.dimension.standard"
class = "Sector"
description = """
Benchmark Commercial Sector
"""

[[dimensions]]
type = "subsector"
name = "AEO2021-commercial-building-types-include-unspecified"
display_name = "AEO Commercial Building Type"
file = "dimensions/aeo2021_commercial_building_types_include_unspecified.csv"
module = "dsgrid.dimension.standard"
class = "Subsector"
description = """
AEO 2021 commercial building types (N=13), include Unspecified
"""

[[dimensions]]
type = "metric"
name = "AEO2021-commercial-energy-enduses"
display_name = "AEO Commercial End Use"
file = "dimensions/aeo2021_commercial_energy_enduses.csv"
module = "dsgrid.dimension.standard"
class = "EnergyEndUse"
description = """
AEO 2021 commercial energy end uses (N=22, from 11 end uses, 3 fuel types)
"""

[[dimensions]]
type = "scenario"
name = "Reference_Scenario"
display_name = "AEO Reference"
file = "dimensions/aeo_reference_scenario.csv"
module = "dsgrid.dimension.standard"
class = "Scenario"
description = """
AEO Reference Scenario
"""

[[dimensions]] # already registered
type = "data_source"
name = "Data-Source-AEO-2021"
display_name = "AEO 2021"
file = "dimensions/aeo2021_data_source.csv"
module = "dsgrid.dimension.standard"
class = "DataSource"
description = """
AEO 2021 Data Source
"""

[[dimensions]]
type = "weather_year"
name = "Weather_Years-trivial-2013_to_2050"
display_name = "None"
file = "dimensions/weather_years_trivial_2013_to_2050.csv"
module = "dsgrid.dimension.standard"
class = "WeatherYear"
description = """
Weather years, 2013-2050, trivial, single record
"""

[[dimensions]]
type = "model_year"
name = "Model_Years-trivial-2013_to_2050"
display_name = "None"
file = "dimensions/model_years_trivial_2013_to_2050.csv"
module = "dsgrid.dimension.standard"
class = "ModelYear"
description = """
Model years, 2013-2050, trivial, single record
"""

[[dimensions]]
type = "time"
class = "AnnualTime"
time_type = "annual"
module = "dsgrid.dimension.standard"
description = "Annual time 2013-2050"
name = "annual_time-2013_to_2050"
display_name = "Annual"
ranges = [{start = "2013", end = "2050"}]
str_format = "%Y"
include_leap_day = true
measurement_type = "total"

