# ------------------------------------------------------
# Base Dimensions
# ------------------------------------------------------
[[dimensions]]
class = "County"
description = """
US counties 2010, no territories, AK, HI, and some other counties, only for ComStock
"""
file = "dimensions/comstock_counties.csv"
module = "dsgrid.dimension.standard"
name = "US Counties 2010 - ComStock Only"
type = "geography"
display_name = "County"

[[dimensions]]
class = "Sector"
description = """EFS Sectors; Residential and commercial only for ComStock"""
file = "dimensions/sectors.csv"
module = "dsgrid.dimension.standard"
name = "EFS Sectors - ComStock Only"
type = "sector"
display_name = "Sector"

[[dimensions]]
class = "Subsector"
description = """Building types subsectors for ComStock, 14 DOE prototypes"""
file = "dimensions/subsectors.csv"
module = "dsgrid.dimension.standard"
name = "ComStock Subsectors EFS"
type = "subsector"
display_name = "ComStock Building Type"

[[dimensions]]
class = "EnergyEndUse"
description = """
Detailed End uses for EFS; ComStock Only
"""
file = "dimensions/enduses.csv"
module = "dsgrid.dimension.standard"
name = "EFS Detailed End Uses - ComStock Only"
type = "metric"
display_name = "ComStock End Use"

[[dimensions]]
class = "WeatherYear"
description = """
Weather year, 2012 only
"""
file = "dimensions/weather_years.csv"
module = "dsgrid.dimension.standard"
name = "2012 Weather Year"
type = "weather_year"
display_name = "2012 Weather"

[[dimensions]]
class = "ModelYear"
description = """
Model years, 2010-2050, every decade
"""
file = "dimensions/model_years.csv"
module = "dsgrid.dimension.standard"
name = "Model Years 2010 to 2050"
type = "model_year"
display_name = "Model Year"

[[dimensions]]
class = "Scenario"
description = """
Reference scenario
"""
file = "dimensions/scenarios.csv"
module = "dsgrid.dimension.standard"
name = "Reference Scenario"
type = "scenario"
display_name = "Reference"

[[dimensions]]
class = "DataSource"
description = """
ComStock only data source
"""
file = "dimensions/data_sources.csv"
module = "dsgrid.dimension.standard"
name = "ComStock Data Source"
type = "data_source"
display_name = "ComStock"

[[dimensions]]
class = "Time"
description = """
Time dimension, 2012 hourly EST, period-beginning, no DST, no Leap Day Adjustment, total value
"""
frequency = "01:00:00"
name = "Time-2012-EST-hourly-periodBeginning-noDST-noLeapDayAdjustment-total"
time_interval_type = "period_beginning"
ranges = [{start = "2012-01-01 00:00:00", end = "2012-01-07 23:00:00"}]
str_format = "%Y-%m-%d %H:%M:%S"
timezone = "EasternStandard"
type = "time"
measurement_type = "total"
time_type = "datetime"
display_name = "2012 Hourly EST"

# ------------------------------------------------------
# Supplemental Dimensions
# ------------------------------------------------------
[[dimensions]]
class = "State"
description = """
US States
"""
file = "dimensions/supplemental/states.csv"
module = "dsgrid.dimension.standard"
name = "US States"
type = "geography"
display_name = "State"

[[dimensions]]
class = "CensusDivision"
description = """
US Census Divisions
"""
file = "dimensions/supplemental/census_divisions.csv"
name = "US Census Divisions"
type = "geography"
display_name = "Census Division"

[[dimensions]]
class = "CensusRegion"
description = """
US Census Regions
"""
file = "dimensions/supplemental/census_regions.csv"
name = "US Census Regions"
type = "geography"
display_name = "Census Region"

[[dimensions]]
class = "Subsector"
description = """
Commercial subsectors
"""
file = "dimensions/supplemental/commercial_subsectors.csv"
name = "Commercial Subsectors"
type = "subsector"
display_name = "Commercial Subsector"

