[[mappings]]
description = "Maps EFS Sectors - ComStock Only (type=DimensionType.SECTOR) to ComStock Subsectors EFS (type=DimensionType.SUBSECTOR)"
file = "dimension_mappings/base-to-base/lookup_sector_to_subsector.csv"
[mappings.from_dimension]
dimension_id = "efs_sectors_-_comstock_only__0f03e3c1-f18b-4ec8-830d-6d93e5e007e3"
type = "sector"
version = "1.0.0"
[mappings.to_dimension]
dimension_id = "comstock_subsectors_efs__f831662d-ce4b-4415-8a97-a33d66257cfe"
type = "subsector"
version = "1.0.0"

[[mappings]]
description = "Maps EFS US Counties 2010 to US Census Regions"
file = "dimension_mappings/base-to-supplemental/lookup_county_to_censusregion.csv"
[mappings.from_dimension]
dimension_id = "us_counties_2010_-_comstock_only__18d04685-34e8-4ff4-a5fb-173d773bbb04"
type = "geography"
version = "1.0.0"
[mappings.to_dimension]
dimension_id = "us_census_regions__899a4862-883d-4f8f-820e-3921db84ea8e"
type = "geography"
version = "1.0.0"

[[mappings]]
description = "Maps EFS US Counties 2010 to US Census Divisions"
file = "dimension_mappings/base-to-supplemental/lookup_county_to_censusdivision.csv"
[mappings.from_dimension]
dimension_id = "us_counties_2010_-_comstock_only__18d04685-34e8-4ff4-a5fb-173d773bbb04"
type = "geography"
version = "1.0.0"
[mappings.to_dimension]
dimension_id = "us_census_divisions__6e2dcd43-5f14-45b1-b850-f289673d89c7"
type = "geography"
version = "1.0.0"

[[mappings]]
description = "Maps EFS US Counties 2010 to US States"
file = "dimension_mappings/base-to-supplemental/lookup_county_to_state.csv"
[mappings.from_dimension]
dimension_id = "us_counties_2010_-_comstock_only__18d04685-34e8-4ff4-a5fb-173d773bbb04"
type = "geography"
version = "1.0.0"
[mappings.to_dimension]
dimension_id = "us_states__2bae0844-b0d3-4bf0-9d15-d9d969dee774"
type = "geography"
version = "1.0.0"
