description = "test project for code development and validation"
name = "test_efs"
project_id = "test_efs"
dimension_associations = ["dimension_associations/sector__subsector.csv", "dimension_associations/data_source__sector.csv", "dimension_associations/data_source__subsector.csv"]


# [datasets]
# benchmark = []
# historical = []

[[datasets]]
dataset_id = "test_efs_comstock"
dataset_type = "sector_model"
model_sector = "cld"
version = "1.0.0"

[dimensions]
[[dimensions.base_dimensions]]
class = "County"
description = """
US counties 2010, no territories, AK, HI, and some other counties, only for ComStock
"""
file = "dimensions/comstock_counties.csv"
module = "dsgrid.dimension.standard"
name = "US Counties 2010 - ComStock Only"
type = "geography"

[[dimensions.base_dimensions]]
class = "Sector"
description = """EFS Sectors; Residential and commercial only for ComStock"""
file = "dimensions/sectors.csv"
module = "dsgrid.dimension.standard"
name = "EFS Sectors - ComStock Only"
type = "sector"

[[dimensions.base_dimensions]]
class = "Subsector"
description = """Building types subsectors for ComStock, 14 DOE prototypes"""
file = "dimensions/subsectors.csv"
module = "dsgrid.dimension.standard"
name = "ComStock Subsectors EFS"
type = "subsector"

[[dimensions.base_dimensions]]
class = "EnergyEndUse"
description = """
Detailed End uses for EFS; ComStock Only
"""
file = "dimensions/enduses.csv"
module = "dsgrid.dimension.standard"
name = "EFS Detailed End Uses - ComStock Only"
type = "metric"

[[dimensions.base_dimensions]]
class = "WeatherYear"
description = """
Weather year, 2012 only
"""
file = "dimensions/weather_years.csv"
module = "dsgrid.dimension.standard"
name = "2012 Weather Year"
type = "weather_year"

[[dimensions.base_dimensions]]
class = "ModelYear"
description = """
Model years, 2010-2050, every decade
"""
file = "dimensions/model_years.csv"
module = "dsgrid.dimension.standard"
name = "Model Years 2010 to 2050"
type = "model_year"

[[dimensions.base_dimensions]]
class = "Scenario"
description = """
Reference scenario
"""
file = "dimensions/scenarios.csv"
module = "dsgrid.dimension.standard"
name = "Reference Scenario"
type = "scenario"

[[dimensions.base_dimensions]]
class = "DataSource"
description = """
ComStock only data source
"""
file = "dimensions/data_sources.csv"
module = "dsgrid.dimension.standard"
name = "ComStock Data Source"
type = "data_source"

[[dimensions.base_dimensions]]
class = "Time"
description = """
Time dimension, 2012 hourly EST, period-beginning, no DST, no Leap Day Adjustment, total value
"""
frequency = "01:00:00"
name = "Time-2012-EST-hourly-periodBeginning-noDST-noLeapDayAdjustment-total"
time_interval_type = "period_beginning"
ranges = [{start = "2012-01-01 00:00:00", end = "2012-01-07 23:00:00"}]
str_format = "%Y-%m-%d %H:%M:%S"
timezone = "EasternStandard"
type = "time"
measurement_type = "total"
time_type = "datetime"

[[dimensions.supplemental_dimensions]]
class = "State"
description = """
US States
"""
file = "dimensions/supplemental/states.csv"
module = "dsgrid.dimension.standard"
name = "US States"
type = "geography"

[[dimensions.supplemental_dimensions]]
class = "CensusDivision"
description = """
US Census Divisions
"""
file = "dimensions/supplemental/census_divisions.csv"
name = "US Census Divisions"
type = "geography"

[[dimensions.supplemental_dimensions]]
class = "CensusRegion"
description = """
US Census Regions
"""
file = "dimensions/supplemental/census_regions.csv"
name = "US Census Regions"
type = "geography"

[[dimension_mappings.base_to_supplemental]]
description = "Maps EFS US Counties 2010 to US Census Regions"
file = "dimension_mappings/base-to-supplemental/lookup_county_to_censusregion.csv"
[dimension_mappings.base_to_supplemental.from_dimension]
name = "US Counties 2010 - ComStock Only"
type = "geography"
[dimension_mappings.base_to_supplemental.to_dimension]
name = "US Census Regions"
type = "geography"

[[dimension_mappings.base_to_supplemental]]
description = "Maps EFS US Counties 2010 to US Census Divisions"
file = "dimension_mappings/base-to-supplemental/lookup_county_to_censusdivision.csv"
[dimension_mappings.base_to_supplemental.from_dimension]
name = "US Counties 2010 - ComStock Only"
type = "geography"
[dimension_mappings.base_to_supplemental.to_dimension]
name = "US Census Divisions"
type = "geography"

[[dimension_mappings.base_to_supplemental]]
description = "Maps EFS US Counties 2010 to US States"
file = "dimension_mappings/base-to-supplemental/lookup_county_to_state.csv"
[dimension_mappings.base_to_supplemental.from_dimension]
name = "US Counties 2010 - ComStock Only"
type = "geography"
[dimension_mappings.base_to_supplemental.to_dimension]
name = "US States"
type = "geography"
