version = "1.0.0"
description = "CONUS 2022 - ComStock end uses (N=21, 4 fuel types)"
dimension_id = "conus_2022-comstock_energy_enduses_kwh__461efa97-86d3-4cfc-a81f-12f3ad1da4d5"
[[registration_history]]
version = "1.0.0"
submitter = "lliu2"
date = "2022-08-01T17:19:32.770059"
log_message = "Initial registration"

