name = "ReEDS PCA"
display_name = "ReEDS PCA"
dimension_query_name = "reeds_pca"
type = "geography"
id = "reeds_pca__d62d05a3-dd84-48d4-84c4-7dd127a3ff8a"
module = "dsgrid.dimension.standard"
class = "GeographyDimensionBaseModel"
description = "ReEDS Power Control Areas"
file = "reeds_pca.csv"
file_hash = "3ccaed370acc4bc7d1169b3e6c1cbf3a90bfe0d3bf5a3e02f3fa5fb6737c0bf6"
