dataset_id = "conus_2022_reference_resstock"
dataset_type = "modeled"
dataset_qualifier = "quantity"
data_source = "resstock"
data_schema_type = "standard"
dataset_version = "1.0.0"
description = "Time-wrapped, simulated on 09/15/2021 using:\nResStock version: https://github.com/NREL/resstock/releases/tag/eulp_final and\nbuildstock version: https://github.com/NREL/buildstockbatch/releases/tag/eulp_res_final \n(Post-processed using AWS SightGlass and notebooks from https://github.com/NREL/SightGlassDataProcessing/tree/agg_for_dsgrid)"
origin_creator = "Lixi Liu"
origin_organization = "NREL"
origin_contributors = [ "Anthony Fortanini", "Lixi Liu", "Noah Sandoval",]
origin_project = "End Use Load Profiles"
origin_date = "2021-09-15"
origin_version = "0.1.0"
source = "s3://eulp/simulation_output/national_runs/resstock/eulp_res_final_2012_dsgrid/"
data_classification = "low"
tags = [ "residential", "conus-2022", "reference", "dsgrid_v0.2.0", "standard_scenarios",]
dimensions = []
trivial_dimensions = [ "sector", "weather_year", "model_year", "scenario", "data_source",]
[[dimension_references]]
type = "geography"
dimension_id = "conus_2022-resstock_us_county_fip__46811eca-4652-4670-8144-30c0f3a6a6da"
version = "1.0.0"

[[dimension_references]]
type = "sector"
dimension_id = "residential-sector__61a436e9-ab46-4122-89ac-492d94d26590"
version = "1.0.0"

[[dimension_references]]
type = "subsector"
dimension_id = "conus_2022-resstock_building_types__ac1f47c2-18d7-4192-a424-623ebc2bbfe8"
version = "1.0.0"

[[dimension_references]]
type = "metric"
dimension_id = "conus_2022-resstock_energy_enduses_kwh__1b980827-4dee-4025-adbc-8488f3377477"
version = "1.0.0"

[[dimension_references]]
type = "data_source"
dimension_id = "resstock-data-source__fba6f013-b047-4384-9079-60337bbec3b9"
version = "1.0.0"

[[dimension_references]]
type = "scenario"
dimension_id = "conus-2022-reference__f32f2c38-c756-4c2e-8fd5-800215af9f1f"
version = "1.0.0"

[[dimension_references]]
type = "weather_year"
dimension_id = "2012_weather_year__387442fa-18fa-4c04-ba36-943f1092fc98"
version = "1.0.0"

[[dimension_references]]
type = "time"
dimension_id = "time-2012-est-8784-hourly-periodending-noleapdayadjustment-total-hour0start__472937bf-d011-4604-8cc2-ed7bc30b2929"
version = "1.0.0"

[[dimension_references]]
type = "model_year"
dimension_id = "model-year-2018__7b7e939d-2ae9-4f82-be65-3236132c28aa"
version = "1.0.0"

[data_schema]
load_data_column_dimension = "metric"

[user_defined_metadata]
