name = "US Census Regions"
display_name = "Census Region"
dimension_query_name = "census_region"
type = "geography"
id = "us_census_regions__b99e65d4-ffb5-4b0c-95ff-c9618f257d27"
module = "dsgrid.dimension.standard"
class = "CensusRegion"
description = "US Census Regions"
file = "census_regions.csv"
file_hash = "15581913f956a82d4fd1a404c8b994ea232536bbf5e5e1947d79371b6dd41e9c"
