version = "1.0.0"
description = "ResStock CONUS 2022 energy end uses mapping to project"
dimension_mapping_id = "conus_2022-resstock_energy_enduses_kwh__conus-2022-detailed-end-uses-kwh__62828091-01e8-4200-a9a0-c4ea000405c1"
[[registration_history]]
version = "1.0.0"
submitter = "lliu2"
date = "2022-08-01T17:26:21.811192"
log_message = "Initial registration"

