name = "ComStock Data Source"
type = "data_source"
id = "comstock_data_source__be98aa91-84dc-4ea2-80b0-2cf4f65c1f09"
module = "dsgrid.dimension.standard"
class = "DataSource"
description = "ComStock only data source"
model_hash = "cadd963b624d3604e5108cf8e9bd51d8945c6e50288db6debb3cfd01904be1c8"
file = "data_sources.csv"
file_hash = "95a87a907929dab0172adde77c629ff535111fb80c83b893985293cba4445ae0"
