version = "1.0.0"
description = "US Census Divisions"
dimension_id = "us_census_divisions__dc625e7c-6c4b-4a3e-84e6-298d08a045c0"
[[registration_history]]
version = "1.0.0"
submitter = "dthom"
date = "2021-09-14T07:51:56.192334"
log_message = "Initial registration"

