name = "Sectors - Com-Res-Tra-Only"
display_name = "Sector"
dimension_query_name = "sector"
type = "sector"
id = "sectors_-_com-res-tra-only__9b09088d-b340-48d1-bc79-52e50989289e"
module = "dsgrid.dimension.standard"
class = "Sector"
description = "dsgrid Standard Scenarios 2021 Sectors; Commercial, Residential, Transportation  Only"
file = "sectors.csv"
file_hash = "8f1a8cc0399e3fab7ce41e28b67df7eea134f62847b3ca07bc9d3aa8646fb4fa"
