version = "1.0.0"
description = "Type of charging (L1 and L2, DCFC) used by TEMPO PEVs."
dimension_id = "tempo_ldv_pev_usage__ef95e63e-2947-46a4-b882-00c3569f48e5"
[[registration_history]]
version = "1.0.0"
submitter = "lliu2"
date = "2022-08-01T17:31:37.822288"
log_message = "Initial registration"

