dataset_id = "tempo_conus_2022"
dataset_type = "modeled"
dataset_qualifier = "quantity"
data_source = "tempo"
data_schema_type = "standard"
dataset_version = "1.0.0"
description = "CONUS 2022 TEMPO county-level results for PEV charging."
origin_creator = "Arthur Yip"
origin_organization = "NREL"
origin_contributors = [ "Arthur Yip", "Brian Bush", "Christopher Hoehne", "Paige Jadun", "Catherine Ledna", "Matteo Muratori",]
origin_project = "dsgrid CONUS 2022"
origin_date = "Dec 21 2021"
origin_version = "dsgrid"
source = "https://github.nrel.gov/mmurator/TMM/commit/54f715e0fe015a578dd0594c7031c046cfe27907"
data_classification = "low"
tags = [ "transportation", "conus-2022", "reference", "tempo",]
dimensions = []
trivial_dimensions = [ "sector", "weather_year", "data_source",]
[[dimension_references]]
type = "geography"
dimension_id = "acs_county_2018__740db19d-2f34-4472-8464-388c4fe96acb"
version = "1.0.0"

[[dimension_references]]
type = "subsector"
dimension_id = "tempo_bin__e4400ab0-2170-40d6-893e-5a1a6abb20b4"
version = "1.0.0"

[[dimension_references]]
type = "metric"
dimension_id = "tempo_ldv_pev_usage__ef95e63e-2947-46a4-b882-00c3569f48e5"
version = "1.0.0"

[[dimension_references]]
type = "time"
dimension_id = "time_of_week_by_month__9e7b2bcd-5143-48e1-be50-70b57f8c17b2"
version = "1.0.0"

[[dimension_references]]
type = "data_source"
dimension_id = "tempo_model__44982884-32a1-45ba-8f89-4bdcd3af7eff"
version = "1.0.0"

[[dimension_references]]
type = "model_year"
dimension_id = "tempo_model_year__294ca699-5fbf-48f8-824b-b788b279bb45"
version = "1.0.0"

[[dimension_references]]
type = "sector"
dimension_id = "transportation_sector__7d8e2795-8de2-42b7-a64b-f6487add2b62"
version = "1.0.0"

[[dimension_references]]
type = "scenario"
dimension_id = "technology_and_policy_scenario__8220772d-4ad4-4e51-afe1-fb6f42f0a30a"
version = "1.0.0"

[[dimension_references]]
type = "weather_year"
dimension_id = "2012_weather_year__387442fa-18fa-4c04-ba36-943f1092fc98"
version = "1.0.0"

[data_schema]
load_data_column_dimension = "metric"

[user_defined_metadata]
