version = "1.0.0"
description = "Maps EFS US Counties 2010 to US Census Divisions"
dimension_mapping_id = "us_counties_2010_-_comstock_only__us_census_divisions__4717fc2d-07ae-497b-badc-6479e9c7aa11"
[[registration_history]]
version = "1.0.0"
submitter = "dthom"
date = "2021-09-14T07:51:56.315948"
log_message = "Initial registration"

