name = "Time of Week by Month"
display_name = "Hourly for Representative Weeks"
dimension_query_name = "hourly_for_representative_weeks"
type = "time"
id = "time_of_week_by_month__9e7b2bcd-5143-48e1-be50-70b57f8c17b2"
module = "dsgrid.dimension.standard"
class = "Time"
description = "TEMPO Time - Month (representing seasons), day of week, and hour of day."
time_type = "representative_period"
measurement_type = "total"
format = "one_week_per_month_by_hour"
time_interval_type = "period_ending"
[[ranges]]
start = 1
end = 12

