mapping_type = "many_to_many_explicit_multipliers"
archetype = "many_to_many_map"
description = "2010-2050 from interpolating for every other year and 0 for 2010-2017"
id = "tempo_model_year__model_years_2010_to_2050__f52e9dea-3ba5-4d4e-ba54-8335faf3ed74"
file = "model_year_to_model_year.csv"
file_hash = "d1e7ee19049f9b896dfc9e33f3e844a4b235f0e6670bd26ee88d757fee51cb9d"

[from_dimension]
type = "model_year"
dimension_id = "tempo_model_year__294ca699-5fbf-48f8-824b-b788b279bb45"
version = "1.0.0"

[to_dimension]
type = "model_year"
dimension_id = "model_years_2010_to_2050__e8f03fb0-c547-403f-bb3b-e11a8cf3df6d"
version = "1.0.0"
