name = "EFS Sectors - ComStock Only"
type = "sector"
id = "efs_sectors_-_comstock_only__dcf07a98-6267-41c7-abb5-647fbd44850b"
module = "dsgrid.dimension.standard"
class = "Sector"
description = "EFS Sectors; Residential and commercial only for ComStock"
model_hash = "67e4cdb38df52f2b3268d406c5814acac9ec1fefb297b35e4538caf61da8ff16"
file = "sectors.csv"
file_hash = "2ab79d94f03eea7c8cb9eae0d93bb68032fca54314aff1d8d1627fce84a532be"
