version = "1.0.0"
description = "CONUS 2022 - ComStock US county in (older version) original FIP code (N=3,133),\nincludes 23 AK counties, 1 county renamed in 2015 (SD, Shannon County -> SD, Oglala Lakota County),\n1 city (VA, Bedford City) that is now part of a county (VA Bedford County)."
dimension_id = "conus_2022-comstock_us_county_fip__e26591ba-2aac-4059-8e45-a79915d6783e"
[[registration_history]]
version = "1.0.0"
submitter = "lliu2"
date = "2022-08-01T17:19:32.770059"
log_message = "Initial registration"

