name = "EFS Detailed End Uses - ComStock Only"
type = "metric"
id = "efs_detailed_end_uses_-_comstock_only__e63b101c-2ab6-4914-bc02-4db1e6440e12"
module = "dsgrid.dimension.standard"
class = "EnergyEndUse"
description = "Detailed End uses for EFS; ComStock Only"
model_hash = "bcf4cd6a7bf19360f2759a7a1426abd52853f64b2cadb99cca764e9aa7ed1e5e"
file = "enduses.csv"
file_hash = "e9b5e4da061670b561e49934027456c00006c50519f3527a15446f8c94de3014"
