version = "1.0.0"
description = "2010-2050 from interpolating for every other year and 0 for 2010-2017"
dimension_mapping_id = "tempo_model_year__model_years_2010_to_2050__f52e9dea-3ba5-4d4e-ba54-8335faf3ed74"
[[registration_history]]
version = "1.0.0"
submitter = "lliu2"
date = "2022-08-01T17:41:38.382597"
log_message = "Initial registration"

