name = "conus_2022-resstock_US_county_FIP"
display_name = "County"
dimension_query_name = "county"
type = "geography"
id = "conus_2022-resstock_us_county_fip__46811eca-4652-4670-8144-30c0f3a6a6da"
module = "dsgrid.dimension.standard"
class = "County"
description = "CONUS 2022 - ResStock US county in original FIP code (N=3,108)"
file = "conus_2022-resstock_geography_county_fips.csv"
file_hash = "e04420940b6ab92577399aa54be6045753852cb45b12e248c5fa7b0da2e60923"
