version = "1.0.0"
description = "TEMPO demographic/geographic/vehicle bins (CONUS 2022) to dsgrid CONUS 2022 Subsectors"
dimension_mapping_id = "tempo_bin__conus-2022-detailed-subsectors__b1c7891f-9067-4386-b433-520eedcc518a"
[[registration_history]]
version = "1.0.0"
submitter = "lliu2"
date = "2022-08-01T17:41:38.382597"
log_message = "Initial registration"

