name = "ComStock Subsectors EFS"
type = "subsector"
id = "comstock_subsectors_efs__acdbd298-44dc-4fa7-b1db-834e4736c3d5"
module = "dsgrid.dimension.standard"
class = "Subsector"
description = "Building types subsectors for ComStock, 14 DOE prototypes"
model_hash = "019018c8c64c4cd14bebf16cd33f5dced24e59e6f8dc40e58d7e4674b8576440"
file = "subsectors.csv"
file_hash = "d31c76bec6c3f8baf009f74cc2f6f951de0e91b50ff0e658e462dbf901def56a"
