version = "1.0.0"
description = "dsgrid Standard Scenarios 2021 Sectors; Commercial, Residential, Transportation  Only"
dimension_id = "standard_scenarios_2021_sectors_-_com-res-tra-only__533c76e9-ee74-48d3-bb6d-5c2774a1d1ec"
[[registration_history]]
version = "1.0.0"
submitter = "mmooney"
date = "2021-09-29T09:19:41.570631"
log_message = "Initial Registration"

