version = "1.0.0"
description = "Maps EFS US Counties 2010 to US States"
dimension_mapping_id = "us_counties_2010_-_comstock_only__us_states__91e10042-e6ef-45a1-95cc-df40c0132a18"
[[registration_history]]
version = "1.0.0"
submitter = "dthom"
date = "2021-09-14T07:51:56.315948"
log_message = "Initial registration"

