name = "Time-2012-EST-hourly-periodEnding-noDST-noLeapDayAdjustment-total-UTChour1start"
type = "time"
id = "time-2012-est-hourly-periodending-nodst-noleapdayadjustment-total-utchour1start__634155b1-c674-4c59-a4bc-e0eb30899de8"
module = "dsgrid.dimension.standard"
class = "Time"
description = "Time dimension, 2012 hourly EST, period-ending, no DST, no Leap Day Adjustment, total value"
model_hash = "7cd62c01e12f2fde98ae411ac5666d31237d48540ee21796d0291951062abec0"
time_type = "datetime"
measurement_type = "total"
str_format = "%Y-%m-%d %H:%M:%S"
frequency = "P0DT1H0M0.000000S"
leap_day_adjustment = "none"
time_interval_type = "period_ending"
timezone = "EasternStandard"
[[ranges]]
start = "2012-01-01 01:00:00"
end = "2013-01-01 00:00:00"

