name = "Time-2012-UTC-houlry-periodBeginning-noDST-noLeapDayAdjustment-mean"
type = "time"
id = "time-2012-utc-houlry-periodbeginning-nodst-noleapdayadjustment-mean__995e057a-ee81-4901-855c-67a6c22f3153"
module = "dsgrid.dimension.standard"
class = "Time"
description = "Time dimension, 2012 hourly UTC, period-beginning, no DST, no Leap Day Adjustment, mean value"
model_hash = "0d9e5f837547a8f1cc6b1642b1b17b923e64e2219bf2c517b12412f4a5213f39"
time_type = "datetime"
measurement_type = "mean"
str_format = "%Y-%m-%d %H:%M:%S"
frequency = "P0DT1H0M0.000000S"
leap_day_adjustment = "none"
time_interval_type = "period_beginning"
timezone = "UTC"
[[ranges]]
start = "2012-01-01 00:00:00"
end = "2012-12-31 23:00:00"

