version = "1.0.0"
description = "Maps US Counties 2020 L48 to State"
dimension_mapping_id = "us_counties_2020_l48__us_states__5f838cf2-bedd-44f0-ab6d-ebe11e773dbe"
[[registration_history]]
version = "1.0.0"
submitter = "lliu2"
date = "2022-08-01T17:19:30.073792"
log_message = "Initial registration"

