name = "Standard Scenarios 2021 DataSources - ComStock-ResStock-TEMPO-Only"
type = "data_source"
id = "standard_scenarios_2021_datasources_-_comstock-resstock-tempo-only__c68a8259-e2cc-468c-b1df-0f4733b2cfeb"
module = "dsgrid.dimension.standard"
class = "DataSource"
description = "dsgrid Standard Scenarios 2021 Data Sources; ComStock, TEMPO, ResStock Only"
model_hash = "3b1eff34de297b34e44b076a246c5a30a526086ad2283f111a34a01d485b439b"
file = "sources.csv"
file_hash = "375cda6b6d3612cc5227f3fac337049691847ac8045970f18072e075c50bb760"
