name = "commercial-sector"
display_name = "Commercial"
dimension_query_name = "commercial"
type = "sector"
id = "commercial-sector__9ad7c682-4713-47dc-b021-42e66fc418c8"
module = "dsgrid.dimension.standard"
class = "Sector"
description = "Commercial sector only"
file = "sector_commercial.csv"
file_hash = "b42fb5813d93fe54621be0b7f787f6282b72cb7f8ff434fa949e543643225620"
