name = "conus_2022-comstock_energy_enduses_kwh"
display_name = "ComStock End Use"
dimension_query_name = "comstock_end_use"
type = "metric"
id = "conus_2022-comstock_energy_enduses_kwh__461efa97-86d3-4cfc-a81f-12f3ad1da4d5"
module = "dsgrid.dimension.standard"
class = "EnergyEndUse"
description = "CONUS 2022 - ComStock end uses (N=21, 4 fuel types)"
file = "conus_2022-comstock_end_uses.csv"
file_hash = "fd435140b7122f087babcf16fb4c7805f73ed9e15c89e3f50a441c8ec9ba00e9"
