name = "Comstock-Data-Source"
display_name = "ComStock"
dimension_query_name = "comstock"
type = "data_source"
id = "comstock-data-source__e44a2040-5965-45a2-935b-06f3eb3c7cf9"
module = "dsgrid.dimension.standard"
class = "DataSource"
description = "Data source: ComStock"
file = "data_source_comstock.csv"
file_hash = "b935653089fd210bdf8223228e506f2b355b49214105344ac174a6dbc469a57c"
